version: "3.3"

services:
  game:
    build: .
    ports:
      - "8079:8079"
    image: maingame:latest
    container_name: maingame
    stdin_open: true
    depends_on:
      - model-api
      - controller-api
      - tui-api
      - gui-api
      - mysqldatabase
      - mongodatabase
    environment:
      - CONTROLLERHTTPSERVER=controller-api:8081
      - GAMEMODE=docker

  mysqldatabase:
    build:
      context: ./DBDockerfiles/MySqlDocker
      dockerfile: ./Dockerfile
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    image: mysqldatabase:latest
    container_name: mysqldatabase

  mongodatabase:
    build:
      context: ./DBDockerfiles/MongoDbDocker
      dockerfile: ./Dockerfile
    ports:
      - "27017:27017"
    security_opt:
      - seccomp:unconfined
    image: mongo:latest
    container_name: mongodatabase

  model-api:
    build:
      context: ./Model
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    image: model-api:latest
    container_name: model-api
    stdin_open: true
    depends_on:
      - mysqldatabase
      - mongodatabase
    environment:
      - DATABASE_HOST=mysqldatabase:3306
      - MYSQL_DATABASE=battleship
      - MYSQL_USER=battleship
      - MYSQL_PASSWORD=battleship
      - MONGODB_HOST=mongodatabase:27017

  controller-api:
    build:
      context: ./Controller
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    image: controller-api:latest
    container_name: controller-api
    stdin_open: true
    depends_on:
      - model-api
    environment:
      - GUIHTTPSERVER=gui-api:8083
      - TUIHTTPSERVER=tui-api:8082
      - MODELHTTPSERVER=model-api:8080
      - GAMEHTTPSERVER=gane:8079

  tui-api:
    build:
      context: ./Tui
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    image: tui-api:latest
    container_name: tui-api
    depends_on:
      - controller-api
      - model-api
    stdin_open: true
    environment:
      - CONTROLLERHTTPSERVER=controller-api:8081
      - MODELHTTPSERVER=model-api:8080

  gui-api:
    build:
      context: ./Gui
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    image: gui-api:latest
    container_name: gui-api
    depends_on:
      - controller-api
      - model-api
    stdin_open: true
    # launch VcXSrv.exe [multiple windows, start no client, Clipboard & Primary Selection & Native Opengl & Disable access control ]
    environment:
      - DISPLAY=host.docker.internal:0.0
      - CONTROLLERHTTPSERVER=controller-api:8081
      - MODELHTTPSERVER=model-api:8080
      - PICTUREPATH=src/main/scala/Battleship/aview/gui/media/BattleShipPicture.png
